var x = 1;
console.log(x);
var s = "Hello World";
var a = 10;
var b = 2;
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(a / b);
console.log(Math.pow(a, b));
console.log(a > b);
console.log(a < b);
console.log(a == b);
console.log(a ^ b);
console.log(a % b);
console.log(s);
console.log(s.toLowerCase());
console.log(s.toUpperCase());
console.log(s.charAt(0));
